### ISSUE TITLE
libGL error: unable to load driver: radeonsi_dri.so etc..

### ISSUE THREAD

**Issue by NikkyAI** [ValveSoftware/portal2#270] opened 2016-07-16 11:01 UTC
running manjaro linux and steam (atm beta but same issue on stable)
using amdpgu on a R9 390

steam fails to load game overlay stuff (soft error i think)
and then portal 2 tries to load graphics drivers faiils and tries to load software graphic drivers

log: http://pastebin.com/t6vzYu5H

portal 1 launches fine and portal 2 on my laptop running the same OS but using intel drivers works too

the game is installed on a external ext4 driver.. i tried using ntfs but then reformatted to eliminate that doubt
it also happens when starting it from steam or running the portal2.sh

**Comment by Tele42** [comment] 2016-07-16 11:23
Hello @Achati, there is a long standing issue with the steam runtime and mesa 10.5 and newer. Does the [Arch workaround](https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Steam_runtime_issues) help?

**Comment by NikkyAI** [comment] 2016-07-16 11:45
this is not starting steam, steam start fine, deleting the libraries fixed the usual steam-not-tarting-issue 
but this appears in the console output when trying to start portal 2
trying out the dynamic linker workaround now

**Comment by NikkyAI** [comment] 2016-07-16 11:48
did not work to run steam using the dynamic linker workaround

**Comment by NikkyAI** [comment] 2016-07-16 11:51
seems like starting aperture: tag seems to work fine, next i will try with portal: stories mel, expecting it to work though.. if so the issue is only with portal 2 failing to load some libs

EDIT: nevermind apertuire: tag crashes after the first two vendor screens.. with this log output: http://pastebin.com/rjjf7ete

**Comment by NikkyAI** [comment] 2016-07-16 15:20
Portal Stories: MEL plays without probllems and i thought i was built ontop of the same engine with minimal adjustements..

**Comment by vfjpl** [comment] 2017-01-20 11:25
https://github.com/ValveSoftware/portal2/issues/267

**Comment by kisak-valve** [comment] 2017-02-03 20:53
Closing as a duplicate of #248.

**Closed as completed by kisak-valve** 2017-02-03 20:53 UTC
