### ISSUE TITLE
Wrong language in Linux beta

### ISSUE THREAD

**Issue by abt462** [ValveSoftware/portal2#42] opened 2014-02-26 11:00 UTC
I have a system (Ubuntu 13.10) in french, Steam is set to french too, Portal 2 beta is set to french in the game properties. Yet, when I launch it, everything is displayed in english (but audio is in french as expected). Not sure if it's a bug or the beta being english only at that time.

**Comment by jacobmischka** [comment] 2014-02-26 11:08
Duplicate of #8

**Closed as completed** 2014-02-26 21:43 UTC
Labels: duplicate
