### ISSUE TITLE
Gamecrash while loading level

### ISSUE THREAD

**Issue by symptog** [ValveSoftware/portal2#132] opened 2014-03-02 10:51 UTC
Hi,

I am unable to start any level, the level is loading till the last 3 loading dots.
then the game is closed and I am back on the desktop

started steam via terminal:

Installing breakpad exception handler for appid(portal2_linux)/version(1.0_client)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197972477886 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561197972477886
CClientSteamContext logged on = 1
Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Game.dll loaded for "Half-Life 2"
/home/tobias/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: Zeile 46: 10297 Abgebrochen             ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 10297 
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0

My System:

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3418 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Linux Mint 13 Maya (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-59-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Muffin
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 6900 Series

```
Driver Version:  4.2.12337 Compatibility Profile Context 8.96.7
OpenGL Version: 4.2
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6718
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20,51" x 11,54"  (23,50" diag)
                                        52,1cm x 29,3cm  (59,7cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  7985 Mb

Miscellaneous:
    UI Language:  English
    LANG:  de_DE.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  938895 Mb
    Largest Free Hard Disk Block:  86014 Mb

Installed software:

Recent Failure Reports:
    Sun Mar  2 10:28:23 2014 GMT: file ''/tmp/dumps/crash_20140302112734_1.dmp'', upload yes: ''CrashID=bp-4be4d425-c156-455f-9cfb-b34102140302''

the dump was created while removing the libMiles.so from the .../Portal 2/bin folder

the games still crashes with and without this file.

**Comment by timjp87** [comment] 2014-03-02 12:18
Duplicate of #4

**Comment by davidw-valve** [comment] 2014-03-05 01:15
Closing as duplicate of #4.

**Closed as completed by davidw-valve** 2014-03-05 01:15 UTC
Labels: duplicate
