### ISSUE TITLE
Graphics issues on linux (solved)

### ISSUE THREAD

**Issue by MachinaeWolf** [ValveSoftware/portal2#269] opened 2016-06-15 04:24 UTC
I'm running steam on slackware 64bit, 8gb ram, intel integrated graphics, i5-2430M. 
Here's a picture of the issue it's not displaying the textures properly.
[http://images.akamai.steamusercontent.com/ugc/443982864945773292/EAD5D1CF912750F7CC897F3BE0140A30502C4C5D/](url)
Here's some errors from portal 2's console 
`Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"
Requesting texture value from var "$basetexture" which is not a texture value (material: dev/constant_color)
KV Conditional: Unknown symbol INPUTSWAPAB
KV Conditional: Unknown symbol INPUTSWAPAB
Steam config directory: /home/todd/.local/share/Steam/steamapps/common/Portal 2/platform/config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res`

**Comment by Tele42** [comment] 2016-06-15 11:26
Hello, you are missing 32 bit libtxc-dxtn which is needed for mesa to render textures properly in Portal.

**Comment by MachinaeWolf** [comment] 2016-06-17 22:31
That worked thanks :) Sorry it took a bit longer than expected to try it out, I had some other linux issues I was working through.

**Comment by evgfilim1** [comment] 2018-01-10 10:27
If the issue is solved, close it. Thanks.

**Comment by kisak-valve** [comment] 2018-01-10 14:51
Closing as this was a system issue. It's worth noting that the s3tc patent has expired and as a result libtxc-dxtn was merged into newer Mesa.

**Closed as completed by kisak-valve** 2018-01-10 14:51 UTC
