### ISSUE TITLE
Portal 2 fails to launch. Ubuntu 16.04

### ISSUE THREAD

**Issue by wthrif** [ValveSoftware/portal2#275] opened 2017-02-03 20:39 UTC
System specs:
Processor: Intel® Core™ i5-2500K CPU @ 3.30GHz × 4 
Graphics: Gallium 0.4 on AMD CAYMAN (DRM 2.43.0, LLVM 3.8.0)

Portal 2 fails to launch and gives the following error:

will@will-Z68A-D3H-B3:~/.steam/steamapps/common/Portal 2$ ./portal2.sh
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  78
  Current serial number in output stream:  79

I don't have the malicious library files that other users have commented on. I've followed advice given here but with no success: http://askubuntu.com/questions/776080/error-you-are-missing-the-following-32-bit-libraries-and-steam-may-not-run-li

**Comment by kisak-valve** [comment] 2017-02-03 20:47
Hello @wthrif, there is a game bundled libstdc++.so.6 that is too old to be used with your version of mesa. Remove `~/.local/share/Steam/steamapps/common/Portal 2/bin/libstdc++.so.6`.

**Comment by kisak-valve** [comment] 2017-02-03 20:49
Closing as a duplicate of #248.

**Closed as completed by kisak-valve** 2017-02-03 20:49 UTC

**Comment by Alazu** [comment] 2017-02-04 12:18
No No no! can't we tell some one at valve HQ to Stop Bundling the libmesa Graphics drivers with their New valve games? Source SDK 2013 Games should stop containing it in their install!! 
I do believe this is inexcusable....  Personally i can't open Counter-Strike Global Offensive/Portal 2/Left 4 Dead 2/Black Mesa/Portal Stories Mel/Stanley Parable/The Beginners Guide all because i have to delete the old Files individually after install. But C.S.S. T.F.2 Left 4 Dead? and Garry's Mod works because they don't enforce it!

**Comment by Alazu** [comment] 2017-02-04 12:19
Luckily i use the Debian cleaning commandline application to remove it for me... cruft.deb. I've seen this problem too often it is not closed until it is truly Fixed! Come on this is Linux we don't need driver half the time, but not all the time.... We don't all run a pure install of Debian or a another BSD...

**Comment by Alazu** [comment] 2017-02-04 12:25
Also what is with the .exe files in the linux installation also? Also i'm not saying that all library included in package is bad, Steam itself that it's hard to sort binaries for certain versions of linux. Certain binaries are okay such as sdl libraries are important. My best solution is to compare somehow the version of the runtimes to what is available to the user in the Distros current repository.

**Comment by njaard** [comment] 2017-06-23 23:48
Fixed with workaround is not fixed.
