### ISSUE TITLE
Unable start local co-op in splitscreen

### ISSUE THREAD

**Issue by supirman** [ValveSoftware/portal2#43] opened 2014-02-26 11:06 UTC
Try run `joy_remap_player_for_controller1 2` in to console command as mentioned [here](http://forums.steampowered.com/forums/showpost.php?p=33423931&postcount=3), it return unknown command

**Comment by kamnxt** [comment] 2014-02-27 20:40
I have the same issue.

**Comment by tgm4883** [comment] 2014-03-02 21:31
I have this issue as well on Linux. I've tried both the above command (which I believe is to do Keyboard+Mouse and Controller) and 2 wireless XBox 360 controllers. The first Xbox 360 Controller works for player 1, but I can't get it to work for player 2 at all. 

I also attempted to load the first coop level and the controller config (from http://forums.steampowered.com/forums/showthread.php?s=5eceb1c425568a4c70f0cde87f3e8692&t=1847904 ) but this failed as well

**Comment by davidw-valve** [comment] 2014-03-05 00:06
Closing as duplicate of #3

**Closed as completed by davidw-valve** 2014-03-05 00:06 UTC
