### ISSUE TITLE
Splitscreen game not working

### ISSUE THREAD

**Issue by marekjedrzejewski** [ValveSoftware/portal2#137] opened 2014-03-03 10:31 UTC
Xbox 360 controller works, but when I try to launch splitscreen by hitting X on it nothing happens.

**Comment by Tele42** [comment] 2014-03-03 13:34
Duplicate of #3 / #43.

**Comment by davidw-valve** [comment] 2014-03-05 00:06
Closing as duplicate of #3

**Closed as completed by davidw-valve** 2014-03-05 00:06 UTC
Labels: duplicate, Reviewed
