### ISSUE TITLE
Portal 2 bundled libstdc++ incompatible with newer mesa

### ISSUE THREAD

**Issue by YodaMix** [ValveSoftware/portal2#248] opened 2015-03-27 06:11 UTC
Hey, I've been attempting to launch Portal 2 on my Ubuntu 14.10 computer and all that it says is 'Preparing to launch Portal 2...', and then closes.
I've verified my game files and I've rebooted my computer multiple times, and I've followed all information given to me on Steam Support (https://support.steampowered.com/view.php?ticketref=9442-ERFZ-8577). It still does not work!

You can find my system information here: https://gist.github.com/YodaMix/8f4e51504d397775cdb7

I hope to hear back from you guys soon

**Comment by at46** [comment] 2015-06-10 16:54
Could be https://github.com/ValveSoftware/steam-runtime/issues/13.
Can you start steam through a terminal and post the output in here when you try to start portal 2?

**Comment by YodaMix** [comment] 2015-06-11 09:43
_UPDATE_
I am now using Ubuntu 15.04, but the problem still persists.
Here is my (new/Ubuntu 15.04) system information;
https://gist.github.com/YodaMix/8d29f22ae07d5ac3fa09#file-ubuntu-15-04-system-information

Here is my terminal output of Steam starting;
https://gist.github.com/YodaMix/bb8b5d184a1b4bff82e3#file-steam-output
Here is my terminal output when starting Portal 2;
https://gist.github.com/YodaMix/94923ece0975ebb7f4cf#file-portal-2-output

Thanks for getting back to me

**Comment by at46** [comment] 2015-06-11 19:07
You could try to launch steam with _LD_PRELOAD='/usr/$LIB/libstdc++.so.6' steam_ or remove the libgcc_s.so, libstdc++.so  and libxcb.so libraries in the steam folder. Either should force steam to use the newer ubuntu libraries instead of steam libraries.

**Comment by YodaMix** [comment] 2015-06-13 06:16
"LD_PRELOAD='/usr/$LIB/libstdc++.so.6' steam" allows Portal 2 to work, and removing those libraries did too.
Thank you very much

**Comment by Eleuin** [comment] 2015-07-03 03:46
yep, this is definitely an issue. libstdc++.so.6 is preventing Portal 2 based games from launching entirely on radeonsi based systems using Mesa >10.1. Noticed this is even the case with the Portal 2 mod "Portal Stories: Mel", removing libstdc++.so.6 fixes the init crashes. Bump, this has been clearly reproduced

**Comment by KuriKai** [comment] 2015-07-03 22:00
This also effects me

**Comment by el-calavera** [comment] 2015-07-05 13:03
This issue just keeps reappearing…

I have been using the workaround from https://wiki.archlinux.org/index.php/Steam#Steam_runtime_issues i.e. deleting the files using the following command:
find ~/.steam/root/ ( -name "libgcc_s.so_" -o -name "libstdc++.so_" -o -name "libxcb.so*" ) -print -delete
This works to get the Steam Client going again after an update, but for Portal 2 to run again you also have to do it for your game library folder instead of ~/.steam/root/
Thanks YodaMix for pointing that out!

**Comment by vfjpl** [comment] 2017-05-14 08:07
I'm also affected. Come one, it's annoying. Just delete libstdc++ from gamerepo. Steam itself ships libstdc++.

**Comment by Plagman** [comment] 2017-07-26 21:58
This should be fixed with today's Portal2 update.

**Closed as completed by Plagman** 2017-07-26 21:58 UTC

**Comment by DidierLoiseau** [comment] 2021-02-25 22:52
It seems I'm having this issue since the last update, although to be honest I probably hadn't played the game since 31/03/2020 (I got an achievement on that date).

Using `LD_PRELOAD` was working but it disabled the Steam overlay, which is inconvenient for community maps.

Removing `libstdc++.so.6` from the Portal 2 folder works.

**Comment by kisak-valve** [comment] 2021-02-25 23:17
Hello @DidierLoiseau, Portal 2 hasn't bundled libstdc++.so.6 since 2017. I'm guessing that it was a leftover from installing the game at some point before this issue was resolved.
