### ISSUE TITLE
Dialogue does not play

### ISSUE THREAD

**Issue by riking** [ValveSoftware/portal2#17] opened 2014-02-25 22:32 UTC
Environment: Intel HD 4000 Graphics
Ubuntu 13.10

---

Putting aside the horribly slow FPS that integrated graphics gives you, no lines of dialogue are playing during the intro, only sound effects.

Turning on closed captioning shows the dialog lines, but they are not audible.

**Comment by timjp87** [comment] 2014-02-25 22:35
Duplicate of #5

**Closed as completed** 2014-02-26 00:19 UTC
