### ISSUE TITLE
Cannot rate maps in 'Test Chamber Evaluation'

### ISSUE THREAD

**Issue by iiv3** [ValveSoftware/portal2#154] opened 2014-03-07 13:46 UTC
From the main menu select 'Community Test Chambers', then 'Play Single Player Chambers', play some map (e.g. quick_play->top rated).
When you finish the map, a menu named 'Play Single Player Chambers' appears (it is also accessible as menu entry if you press ESC during gameplay). Among other things that menu have 2 huge buttons with thumbs up and thumbs down.
Clicking over these buttons have no effect. Under windows, moving mouse over them changes their color and pressing one of them rates the map. Under linux moving mouse over them have no effect at all.

I'm using "Portal 2 (Beta) [beta]" as I couldn't even start the "Portal 2 (Beta)" when I tried it at first.

**Comment by timjp87** [comment] 2014-03-07 14:15
Duplicate of #144. Not sure why it was closed  by @davidw-valve.

**Comment by iiv3** [comment] 2014-03-07 16:06
@blackout24, this explains why I didn't spot the #144 bug report when I was looking up for similar issues.

@davidw-valve , it might be better idea to mark issues that are fixed in your development build with some tag (e.g. "resolved") and close the bug when the build is released.
As long as the users encounter these bugs, the issue is still open. If issue is closed and the bug is still encountered by the users, then it only means that it haven't been fixed successfully.

**Comment by davidw-valve** [comment] 2014-03-07 17:36
#144 was closed because I believed it to be fixed in the released version. Before changes have been released they are marked as "Next Release".

I will look into why this bug still isn't resolved for you.

**Comment by iiv3** [comment] 2014-03-08 01:06
This is the current running version I'm using. I've seen it autoupdate few times and the settings are still set to autoupdate.

> ]version 
> Protocol version 2001
> Exe version 2.0.0.1 (portal2)
> Exe build: 13:33:08 Feb 27 2014 (5591) (620)

While testing one more time, I discovered that having the cursor around the letters "TES..." highlights the thumb-up button, and having it around " CHA.." highlights the thumb-down one.

I'm running at 1280x720 resolution (16/9 aspect).
If I switch to 1920x1080 (native) the buttons seems to work fine.

**Comment by davidw-valve** [comment] 2014-03-10 21:15
Thank you for the details, helped me track this down. Expect it to be fixed in the next update.

**Comment by davidw-valve** [comment] 2014-03-10 22:00
This should be fixed in the latest update.

**Closed as completed by davidw-valve** 2014-03-10 22:00 UTC
Labels: Reviewed
