### ISSUE TITLE
Bodgy Fonts

### ISSUE THREAD

**Issue by SleepyAkubi** [ValveSoftware/portal2#35] opened 2014-02-26 07:58 UTC
IDK why it is but on every Source game the fonts are drastically different from the Linux version to the Windows version.
![font](https://f.cloud.github.com/assets/3485737/2267654/b72e3708-9ebb-11e3-9396-5f52ec1d310a.png)

I feel it should just be different. It just doesn't feel right to me.

**Comment by timjp87** [comment] 2014-02-26 08:54
The width of your letters seems narrower than on my system. That's why it might look a bit crammed to you. Everything looks fine on my end, but I'm running it on 4x the resolution. 

![bildschirmfoto von 2014-02-26 09_50_51](https://f.cloud.github.com/assets/3089763/2268063/a46a0978-9ec3-11e3-9acf-b513d5ae9a57.png)

**Comment by abt462** [comment] 2014-02-26 10:57
Same problem for me: the font doesn't seem to be the one used on Windows (same one than func-boncey). Not sure if it's a real bug or just Valve using different fonts on different systems but I doubt it's normal.

**Comment by ZeXx86** [comment] 2014-02-26 12:12
Same here, 1920x1200 on my display + nvidia.

**Comment by abt462** [comment] 2014-02-26 12:26
BTW, blackout24: on your capture, the font is indeed wider but it's not the right one either. The problem is not that the menu seems "crammed" but that it's not the right font in either capture. As a reference, search for "portal 2 menu" on Google, you'll find a proper capture of what we should have (e.g. http://www.mobygames.com/images/shots/l/507657-portal-2-windows-screenshot-main-menus.jpg). Look at the shape of the O or the Q, they're quite specific and easier to check.
It looks like the game is simply using the default system font (which won't be the same on every Linux distro: Ubuntu uses the Ubuntu font, some use DejaVu, some use Droid, etc.).

**Comment by stevethepocket** [comment] 2014-03-01 23:23
Confirmed on Kubuntu 14.04 Alpha 2.

The proper font is some form of [Univers](http://www.myfonts.com/fonts/linotype/univers/), by the way. I found the files in /platform/vgui/fonts; they're in some weird format called "vfont". For some reason, the Linux version is unable to read them apparently.

**Comment by peterson-dane** [comment] 2014-03-06 02:49
I can also confirm this issue; it was one of the first things I noticed, in fact. Running Ubuntu 13.10 64-bit on an Intel Core i7 2700K with AMD RadeonHD 6970 graphics card and fglrx version 13.101 (current version from the Ubuntu repos).

**Comment by stevethepocket** [comment] 2014-03-06 03:27
Oddly enough, the font used in the credits (Consolas) is the same in both versions, albeit rendered at a slightly different scale. Despite being also stored as a .vfont file.

**Comment by davidw-valve** [comment] 2014-03-11 20:26
This is fixed in the latest update.

**Closed as completed by davidw-valve** 2014-03-11 20:26 UTC
Labels: Reviewed

**Comment by SleepyAkubi** [comment] 2014-03-12 00:42
Thanks david!
