### ISSUE TITLE
Portal 2 Authoring Tools Model Viewer NOT WORKING

### ISSUE THREAD

**Issue by N0TaD0G** [ValveSoftware/portal2#344] opened 2021-03-04 13:32 UTC
![picture](https://user-images.githubusercontent.com/80046889/109971233-4963ac00-7cf6-11eb-8b45-50938e8b2f18.PNG)

BUG:
Since the newest update (2021.March.02) the Portal 2 Authoring tools Model Viewer won't start.

Additional context: not linux specific, it seem this problem only occur on Windows 10.
I tried to fixing it by doing the verify game cache, but it did nothing.
Also i does not give any error message, it just not loading in, but Hammer and the Faceposer works just fine.

**Comment by KrisCatboy** [comment] 2021-03-07 07:46
The model viewer works fine for me, which is strange. Maybe the issue is OS/hardware specific? I'm running Windows 7.

**Comment by N0TaD0G** [comment] 2021-03-07 10:22
That is maybe the case... im on Win 10.

**Comment by darvil82** [comment] 2021-03-07 11:45
I'm also experiencing this issue in Windows 10.

**Comment by misyltoad** [comment] 2021-03-07 19:42
This should be fixed in the next update.

**Comment by N0TaD0G** [comment] 2021-05-19 10:26
Cool ... looks like its working again, great job guys! :D

**Closed as completed** 2021-05-19 10:42 UTC
Labels: not linux specific
