### ISSUE TITLE
Crash right after level load is completed (except level "The Fall")

### ISSUE THREAD

**Issue by 0x7CFE** [ValveSoftware/portal2#120] opened 2014-03-01 14:19 UTC
Hi guys. Strange issue here.

OS: Kubuntu 13.10 x64
CPU: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
RAM: 8 GB
Graphics: Radeon 7970, 3GB video RAM firegl driver
Game video: all at max
Steam: latest

Game is started, I select "New Game" and the very first level. Game displays loading splash, updates the progress and then at the very end (when the actual game should kick in) all crashes.

This happens for almost every level that I may choose except for "The Fall" which surprisingly works fine. During that level all works brilliant, no lag or graphic artifacts even on the "all enabled" settings. Sound is also ok. After fall all crashes exactly the same way as other levels.

Hope this helps.

```
$ ./portal2_linux -game portal2
SDL video target is 'x11'
SDL video target is 'x11'

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system DOES NOT support the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Using breakpad crash handler
Setting breakpad minidump AppID = 620
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198084305773 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198084305773
Did not detect any valid joysticks.
Did not detect any valid joysticks.

CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)


 ##### swap interval = 1     swap limit = 1 #####
CClientSteamContext logged on = 1
CClientSteamContext logged on = 1

Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)

Game.dll loaded for "Half-Life 2"
Game.dll loaded for "Half-Life 2"

Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 14: reading configurations from ~/.fonts.conf is deprecated.
Unable to remove /storage/data1/korvin/steam/SteamApps/common/Portal 2/portal2/textwindow_temp.html! (errno 2)
Unable to remove /storage/data1/korvin/steam/SteamApps/common/Portal 2/portal2/textwindow_temp.html! (errno 2)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198084305773 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198084305773
Aborted (core dumped)
```

**Comment by timjp87** [comment] 2014-03-01 14:22
Probably related to the other AMD driver issues in #4

**Comment by davidw-valve** [comment] 2014-03-04 20:07
Closing as duplicate of #4

**Closed as completed by davidw-valve** 2014-03-04 20:07 UTC
Labels: duplicate, Reviewed
