### ISSUE TITLE
English audio not work for other-languages Steam client

### ISSUE THREAD

**Issue by Kryuko** [ValveSoftware/portal2#96] opened 2014-02-28 08:53 UTC
Same as title.
I've an Italian Steam client, and when i go to audio settings of Portal 2, the "audio language" is set to "italian", but anyone know there's not any italian audio, so the game voices don't work.
If i set the language to english, when i restart the game is set to italian again, and you know is necessary  restart the game whe you change language.

**Comment by timjp87** [comment] 2014-02-28 10:24
I don't have an "Audio Language" setting in the Audio settings ingame menu. I simply right click Portal 2 in the library -> Properties -> Language and select the language from the dropdown menu. It will have to download 650 MB before the changes take effect.

**Comment by Kryuko** [comment] 2014-02-28 10:36
If you have a not-english language, go to audio, and now you have the option "audio language".
The problem is you can not change it to english, so you don't have any audio-dialog in all the game.

**Comment by davidw-valve** [comment] 2014-03-05 01:29
Do you still repro this problem? I could not reproduce it. It plays the audio in English even if I configure the audio to be Italian in both the steam client and the game.

**Comment by Kryuko** [comment] 2014-03-05 08:49
I'm uploading a youtube video right now.

**Comment by Kryuko** [comment] 2014-03-05 08:56
Video of the bug here: http://www.youtube.com/watch?v=fNE__50adEM&feature=youtu.be

**Comment by laarmen** [comment] 2014-03-05 16:55
FWIW, I have the same problem with French. Even though the French audio does exist, it doesn't switch to English when changing the audio language in the settings. Furthermore, when I agree to restart the game, it doesn't restart but just exits.

(Debian 64-bits unstable, with my ~/.steam symlinked to /var/lib/steam on another partition, in case it is relevent)

**Comment by SymLynks** [comment] 2014-03-06 14:25
Same here for German client. I prefer the English audio, but the setting won't stick.

**Comment by Kryuko** [comment] 2014-03-07 19:06
Now, with the latest update, i don't have the option for audio-language-switching. So the audio language is set to italian, and obviously it doesn't exist and doesn't work.
Please, fix it, i want the audio in the game.

**Comment by davidw-valve** [comment] 2014-03-10 18:20
I'm having trouble reproducing this.

If I set my Steam client to Italian, and Portal 2 to run in Italian, all the menu items are in Italian, but in game the English voices are used.

Do you have any way of getting voices to be heard? Perhaps by setting your Steam client to English? I'm wondering because I'm considering this perhaps isn't an internationalization issue and is simply an issue with our voice playing code.

**Comment by Kryuko** [comment] 2014-03-10 20:47
Yep, your right.
Same problem with english game and client.

**Comment by davidw-valve** [comment] 2014-03-10 20:52
Did you install Portal 2 right when it was released on Linux? There was a bug where one of the audio libraries (libMiles.so) was mis-named as libmiles.so. Could that be your problem here? You can re-name the file yourself or you can delete Portal 2 and reinstall.

See #5 for the details on that and please let me know if it is your issue.

**Comment by Kryuko** [comment] 2014-03-10 20:59
Solved for me with renaming, thanks!

**Comment by davidw-valve** [comment] 2014-03-10 21:00
Glad that worked for you. Closing as duplicate of #5.

**Closed as completed by davidw-valve** 2014-03-10 21:00 UTC
Labels: duplicate, Reviewed
