### ISSUE TITLE
Mouse look direction does a 180 at times

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/portal2#16] opened 2014-02-25 22:21 UTC
At times when playing, the look direction does a complete 180 degree rotation.

**Comment by johndrinkwater** [comment] 2014-02-25 22:38
Noticed this after interaction with the overlay (pressing F12, or getting updates on screenshot upload, etc)
*Played the game with a gamepad, so its likely whenever I used keyboard it triggered mouse/kb input?

**Comment by Arbitrary007** [comment] 2014-02-26 03:05
I do not have the 180 degree turn, though my mouse look does shift to the right about ten degrees when I go through an emancipation grill.

**Comment by ghost** [comment] 2014-02-26 03:09
I get the same issue as Arbitrary007 but not just for emancipation grills only -- it just seems to happen at random.

**Comment by ghost** [comment] 2014-02-26 03:24
180 degrees was just a number off the top of my head. It's completely random for me. Happens randomly, sometimes _a lot_. Flippety flopping like crazy. Happens even with overlay disabled.

**Comment by Arbitrary007** [comment] 2014-02-26 03:45
I'll be doing some extra experimentation on this later this evening.

**Comment by ghost** [comment] 2014-02-26 04:43
Do betas have debug symbols? This bug just screams Valgrind me!

**Comment by Arbitrary007** [comment] 2014-02-26 06:38
Alright, after playing farther into the game and observing some times it occurs, I'm thinking it might have something to do with collision events and how they're handled. Not only do emancipation grids make my view jump, but sometimes I notice the collisions between objects make them jump around while I hold them. When I manage to complete some laser puzzles, particularly with the laser triggers that stick up out of the ground and spin when lit, my view might jump right as well. I've noticed a few times traveling down in the elevator between levels also triggers them with less frequency.

The only events that tend to consistently trigger my view to look right is the emancipation grid, especially if right in front of stairs before an elevator.

**Comment by Arbitrary007** [comment] 2014-02-26 06:42
And to clarify, it's between objects in hand and the floor/environment that make them jump. I know there is supposed to be some jumpiness, but comparing what I recall between PS3 and this version, it feels as though something may be off.

Of course, I could be imagining things with the collisions. The vision jumps, however, are frequent enough that they aren't imagined. It happens at least once per test chamber, usually at the end towards the grid.

**Comment by Mortal** [comment] 2014-02-26 07:57
I have the same issue. With my default sensitivity settings, the view seems to jump at random, but setting the sensitivity way down I notice my view jumps to the right and a bit down. However, for me this happens about once a second, making the game unplayable at the moment.

**Comment by ghost** [comment] 2014-02-26 08:05
There is something to Arbitrary007's theory. Holding things feels very wierd. Objects stutter in the air when moving and the mouse flip happens a lot when holding things. Where I'm just now I get this bug once a second too, not playable right now.

**Comment by jacobmischka** [comment] 2014-02-26 11:21
This is relatively common for early in development FPSes, where the game will lag or hang and the mouse input that was recorded on the frame the hang occurs seems to be simply duplicated for every frame of lag. That's why a lower sensitivity results in much smaller jumps. I didn't experience the jumpiness when playing Portal 2, but I know exactly what you're talking about as I have experienced it in other FPS alpha/betas.

**Comment by bespokebob** [comment] 2014-02-26 12:58
I'm seeing something similar. It's not 180 degrees, and it's not while I'm holding anything. I'm usually just standing still and the camera will jerk in some direction. There's also usually some visual artifact at the same time, like the camera passing through an object or something. I've seen it happen in the starting room, the first test chamber, the elevator after the first test chamber...it's fairly random (yay for non-reproducible bugs)

**Comment by Arbitrary007** [comment] 2014-02-26 15:01
@youngbob I'm beginning to think that there may be something up with the collision checks and the camera. Is it possible that the game is treating the camera as an object that can collide with other objects for half a second? It would explain a few things. I also notice that catching things midair is tricky, and traveling in the air swiftly with objects tends to make them move around a lot on screen.

Or... could something be up with collisions in regard to Chell?

**Comment by dromer** [comment] 2014-02-26 15:22
It seems more like a ~120-degree turn (usually to the right) that happens near emancipation grids and portals.
Definitely not a delay/lag in mouse/controller movement.

**Comment by ghost** [comment] 2014-02-26 22:43
You know the degree doesn't matter. It's not a defined value but rather undefined as if you where reading from an uninitialized buffer, or something time-dependent. We all have the same bug.

**Comment by davidw-valve** [comment] 2014-02-26 23:17
I'm not able to reproduce this. It would be helpful if people could help piece together answers to the following questions: Does it occur at any time, or only when passing through an emancipation grid? Does it happen _every_ time you pass through an emancipation grid? Is it linked to controller use, or does it even happen with no controller even attached to the machine? Does it still occur if you disable the steam overlay in game?

**Comment by ghost** [comment] 2014-02-26 23:20
It happens at any time but especially (but not always) when passing an emancipation grid. So it's completely undefined as far as I understand.

Does it occur at any time, or only when passing through an emancipation grid? Any time.
Does it happen every time you pass through an emancipation grid? No.
Is it linked to controller use, or does it even happen with no controller even attached to the machine? No controller attached.
Does it still occur if you disable the steam overlay in game? Yes.

I use Fedora 20 with GNOME 3.10.2 and Intel graphics drivers (Mesa 9.2.5).

**Comment by bespokebob** [comment] 2014-02-26 23:29
I have seen it occur when standing completely still, nowhere near an emancipation grid. For me, it's about 45 degrees to the right. I'll try disabling the steam overlay...

**Comment by bespokebob** [comment] 2014-02-26 23:51
It still occurs with the steam overlay disabled.

I just sat and reproduced this about a dozen times in the same location (descending the elevator to test chamber 01)
- When the level loads, I stop touching the keyboard and mouse to have a stable frame of reference
- After about 30-60 seconds, the camera jumps about 45-90 degrees clockwise
- After another 30-60 seconds, it happens again
- It doesn't appear to happen a 3rd time (at least, in my 5-minute attention span)

The amount the camera turns doesn't seem 100% random. Although it doesn't always turn the same amount, I noticed that it usually ends up pointing in one of a few specific directions. The amount of time needed is, as far as I can tell, random within the range of a minute or so.

**Comment by bespokebob** [comment] 2014-02-27 00:10
I took some screenshots (after re-enabling overlay). The 3 different "Jump 1" screenshots were from 3 completely different runs, and they appear to be identical.

[Original position](http://steamcommunity.com/sharedfiles/filedetails/?id=232530266)

[Jump 1](http://steamcommunity.com/sharedfiles/filedetails/?id=232530227) (1)
[Jump 1](http://steamcommunity.com/sharedfiles/filedetails/?id=232530286) (2)
[Jump 1](http://steamcommunity.com/sharedfiles/filedetails/?id=232531800) (3)

[Jump 2](http://steamcommunity.com/sharedfiles/filedetails/?id=232530311)

**Comment by jacobmischka** [comment] 2014-02-27 00:33
Would you care to record a demo of the bug? You can start a recording with "record [name of recording]" and finish it with "stop" in the console. I have attempted to replicate, and was unable to do so. If anyone wants to look at my demo, it's available here http://www.mischka.info/things/mousejerktest.dem . Also, it should be mentioned that he is referring to the Portal 1 Test Chamber 01, the one at map sp_a1_intro2. I initially tested with the other Test Chamber 01, the one after getting the portal gun. 

I'm using Ubuntu 13.10 amd64, Nvidia gpu, max graphical settings.

**Comment by bespokebob** [comment] 2014-02-27 01:00
Neat. It was, of course, much harder to reproduce the issue while I was recording it. I still got 3 runs, though the mouse was jerking to a different angle than my previous screenshots.
- [Run 1](https://www.dropbox.com/s/enld3g96v0jyvh3/mousejerk1.dem)
- [Run 2](https://www.dropbox.com/s/r7rykg9v0a90b14/mousejerk2.dem)
- [Run 3](https://www.dropbox.com/s/d1lypjffbgoui1v/mousejerk3.dem)

Sorry, I should have been more specific with the map name. You're right, this is at the beginning of sp_a1_intro2. I haven't been able to get very far due to segfaults and other issues, so I'm still hanging out in the jungle. I've been able to reproduce the issue in plenty of places (starting with the very first room), I've just been using this location as a convenient reference.

**Comment by jacobmischka** [comment] 2014-02-27 02:06
It actually has happened to me a couple times now, though only immediately after loading a map. I don't know why, and I can't reproduce it reliably. I noticed it happened a few times when loading intro7, so [I recorded me completing intro6](http://www.mischka.info/things/mousejerk.dem), and [you can see it happen at the beginning of intro7](http://www.mischka.info/things/mousejerk_2.dem). It's happened a few times right away when loading intro7 via the console, though not consistently. I haven't been able to get it to do it again for about 20 minutes. 

If you watch the intro6 one (which you don't have to really), please ignore the fact that I'm retarded for the first minute or so. 

Edit: It's worth noting that at the time, I didn't see any game video until after I was already looking to the right, unlike in the demo where you see everything, even the smoothed movement.

**Comment by ghost** [comment] 2014-02-27 02:07
FWIW, here is a manual recording: https://drive.google.com/file/d/0B7XfgZAvKYVTU29ub1pWWllyYk0/edit?usp=sharing

**Comment by jacobmischka** [comment] 2014-02-27 02:08
Wow, that's much different and slower than what I experienced and imagined.

**Comment by pilot51** [comment] 2014-02-27 02:25
This happened to me randomly in Test Chamber 02. It is very close to 180 degree flip, but slightly off and the aim drops down a little each flip. When I exited to the main menu and reloaded the level, the flipping was still happening. I recorded a demo, though when playing it back I noticed there's some motion smoothing going on (no surprise), where it was originally an instant flip.
https://dl.dropboxusercontent.com/u/18143123/portal2_issue16.dem

**Comment by ghost** [comment] 2014-02-27 02:35
Since Issue #2 has been fixed and I now can change my resolution to 1280x720 (from 1920x1080) I get better performance and this issue with mouse flipping doesn't happen to me anymore (not yet). So maybe Valve should try to find a slow computer when trying to reproduce this. I guess they aren't developing on an integrated Intel-a-la-20-FPS-machine.

**Comment by Tele42** [comment] 2014-02-27 02:57
I just finished casually walking through chapter 1 and had the direction I was facing change unexpectedly 3 times, all three times appeared to be at the start of a scripted event / dialog

**Comment by Arbitrary007** [comment] 2014-02-27 03:10
I am also seeing similar occurrences as @Tele42. In between lines of dialogue (where the subtitles would bring up a new line). I also checked with one emancipation grid, and it only shifted my vision the first one or two times. Afterwards, it had no effect. I also noticed that these shifts occurred more often when in larger rooms with greater expanses and more numerous objects.

**Comment by Arbitrary007** [comment] 2014-02-27 04:03
While testing for a few other things, I watched for dialogue switches and jumps in view. The random ones that appear to occur when the player is putting in no input have definite ties to the dialogue in the game. The dialogue switches don't always trigger a view shift, but all shifts when the player isn't doing anything do appear to be tied to new lines of dialogue.

**Comment by davidw-valve** [comment] 2014-02-27 17:19
Is there any output in the in-game console or on the terminal when these flips occur?

**Comment by jacobmischka** [comment] 2014-02-27 19:53
No, nothing special that I noticed.

**Comment by kamnxt** [comment] 2014-02-27 20:40
Same issue here.

**Comment by davidw-valve** [comment] 2014-02-27 21:49
Another question: Does this issue occur both in fullscreen and windowed mode?

**Comment by Tele42** [comment] 2014-02-27 22:16
@davidw-valve I was playing fullscreen, native resolution - 1920x1080, primary monitor of a two screen setup.

**Comment by nmiell** [comment] 2014-02-27 22:16
I've experienced this multiple times and have a save right before a 100% reproducible test case in sp_a1_wakeup. 

Looking slightly to the left of GLaDOS's head when you first see it laying on the ground causes the camera to spin around (and it doesn't matter which side you approach the "bad" area of the screen from); after the circuit breaker sequence and while the wakeup animation plays pointing the crosshair at GLaDOS's body causes spins and this seems to keep happening up until the "Oh, it's you" line plays (although it stopping after that VO plays may just be my imagination).

The distance skipped seems to be much more pronounced when in 1080p fullscreen than in a 720p window, so maybe this is a performance-related movement interpolation problem?

**Comment by Arbitrary007** [comment] 2014-02-27 22:35
I have been playing 1600x1200 fullscreen native. One monitor. I will be testing in windowed mode as well as watching for anything funny on the terminal.

**Comment by davidw-valve** [comment] 2014-02-27 22:43
nmiell: can you by chance make a video of exactly what you are doing to repro this? I tried your directions but could not repro it.

**Comment by Arbitrary007** [comment] 2014-02-28 00:25
Interesting fact: I'm playing 800x600 windowed mode and this problem is NOT happening to me anymore. Frame rate is a little lower, but that happens with all the games I play windowed. Also, 1024x768 works fine as well. Not once did my vision shift.

**Comment by ghost** [comment] 2014-02-28 00:51
@Arbitrary007 You cannot draw a valid conclusion from this, since you did _two_ things: change resolution AND switch to windowed. Just like I, we are both not getting this issue anymore, but that's probably not because you changed to windowed but rather because you lowered the resolution thus getting fewer pixels to render. See my previous comment.

**Comment by ghost** [comment] 2014-02-28 01:02
Another question: Does this issue occur both in fullscreen and windowed mode? Yes.

I can reproduce this in 1920x1080 windowed and fullscreen but almost never in 1280x720 fullscreen (haven't tested windowed). This is in my view strong suggestion for a lag/performance dependent issue. (I don't even get flipping when passing emancipation grills in 720).

**Comment by Arbitrary007** [comment] 2014-02-28 01:06
@alexhultman Understood. The good news is, I can test both. Will now test full resolution windowed and lower resolutions at full screen on my end.

Side note: Returning to full screen 1600x1200 brings back the jumping view.

**Comment by davidw-valve** [comment] 2014-02-28 01:07
It's possible this is performance related. What kind of performance do you get when encountering this? Is there any drop in FPS when encountering these issues?

**Comment by Arbitrary007** [comment] 2014-02-28 02:09
There's generally a little drop in FPS when running native at full screen. Further testing revealed the following results:

Windowed @ 1600x1200: SEVERE FPS drop (20-5 fps) and vision jumping (almost once every second or two). Game is almost unplayable it is so bad.
Full screen @ 800x600: Very smooth (65-35 fps) and no vision jumps.
Full screen @ 1024x768: Smooth (45-25 fps) without vision jumps.

Previous tests (with FPS evaluations) are as follows (so they're all in one post for easy viewing):

Full screen @ 1600x1200: 30-20 fps with vision jumping
Windowed @ 600x800: ??? (fps was ALL over; 110 peaks; <30 dips) with no vision jumping
Windowed @ 1024x768:  45-25 fps with no vision jumping

All tests were performed at medium graphics settings except for shading at low. (These settings, for the record, have been constant throughout all times playing for me. I changed them in an early attempt at fixing an earlier issue that has since been remedied. I also have a weaker video card, an nVidia GeForce 210.)

EDIT: Put in actual FPS ranges found since I found a way to display FPS.

**Comment by davidw-valve** [comment] 2014-02-28 03:19
Those who have this problem, can you tell me what the contents of your /sys/devices/system/clocksource/clocksource0/current_clocksource  file is?

**Comment by Tele42** [comment] 2014-02-28 03:44
$ cat /sys/devices/system/clocksource/clocksource0/current_clocksource 
tsc

**Comment by nmiell** [comment] 2014-02-28 05:13
tsc, and it only happens for me when the framerate dips below 30 (which reliably happens looking in a particular direction in the GLaDOS wakeup chamber) and doesn't happen at all if I drop all the quality settings to low and the game runs at 45-60 fps.

**Comment by ghost** [comment] 2014-02-28 05:25
[alexhultman@localhost ~]$ cat /sys/devices/system/clocksource/clocksource0/current_clocksource 
tsc

**Comment by dromer** [comment] 2014-02-28 10:34
$ cat /sys/devices/system/clocksource/clocksource0/current_clocksource
hpet

I tried reducing the resolution down a notch (1440x900) which helps with most of the twitching, but near companion cubes and heavy scripted events things go haywire again.

**Comment by jacobmischka** [comment] 2014-02-28 11:21
Current clocksource is tsc for me, though again it only very very rarely happens to me.

**Comment by davidw-valve** [comment] 2014-02-28 22:46
From the limited amount I was able to reproduce this, I've made a fix, and an update has just been released with this fix.

I'd appreciate it if anybody who has been experiencing this problem would try the update and let me know in this thread if it seems to fix it.

**Comment by nmiell** [comment] 2014-02-28 22:57
I'm no longer able to reproduce this issue with build 202448.

**Comment by dromer** [comment] 2014-02-28 23:26
The direction turning no longer happens for me in native resolution (1680x1050) after this fix.
The game doesn't run perfectly yet, but that's for another topic :)

Any explanation on what the fix entailed?

**Comment by ghost** [comment] 2014-02-28 23:50
Issue is fixed for me. Great work!

**Comment by davidw-valve** [comment] 2014-02-28 23:51
It sounds like it's fixed so I'm closing this.

**Closed as completed by davidw-valve** 2014-02-28 23:51 UTC
