### ISSUE TITLE
Cant find portal2.sh

### ISSUE THREAD

**Issue by marcus15a** [ValveSoftware/portal2#131] opened 2014-03-02 07:54 UTC
https://www.youtube.com/watch?v=20QUIrQClig&feature=c4-overview&list=UUQkst-m_zzg9izAcc3IkYoA

**Comment by LinuxPony** [comment] 2014-03-02 09:19
Have you opted into the beta?

**Comment by marcus15a** [comment] 2014-03-02 09:31
Now tried it, downloaded some updates and the menu working , but when in Single Play i click for New Game the game Crash, now i have this message on terminal:
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198010594209 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198010594209
CClientSteamContext logged on = 1
Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Game.dll loaded for "Half-Life 2"
/home/marcus15/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: 46. sor: 30620 Félbeszakítva         (core készült) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 30620

**Comment by timjp87** [comment] 2014-03-02 12:18
Let me guess. AMD catalyst driver? 
You should provide your system information by going to "Help" -> "System Information" in the Steam client. Right click -> Copy all and paste it here.
Probably duplicate of #4

**Closed as completed** 2014-03-04 00:10 UTC

**Comment by marcus15a** [comment] 2014-03-04 06:33
Yes Amd CCC 13.12 Graphic card HD 6670
