### ISSUE TITLE
Disappearing textures

### ISSUE THREAD

**Issue by marekjedrzejewski** [ValveSoftware/portal2#151] opened 2014-03-05 18:47 UTC
Aaand once again: prison escape (act1) ( http://steamcommunity.com/sharedfiles/filedetails/?id=80745172 )

Half of door at the end of elevator room is black, and the surrounding of elevator also disappears when in the middle of the stairs:

http://youtu.be/lazG4bRKjAE

Didn't record it, but when I come back there it doesn't appear again.

**Comment by marekjedrzejewski** [comment] 2014-03-06 07:41
Probably that's duplicate of  #150 because the ring around elevator gets black because of screens turning off.

**Comment by mariodonofrio** [comment] 2014-03-07 15:04
Do you mean the same as #150 since the video you link to is not a bug but just the monitors turning off as you climb the stairs away from the elevator, same as on Windows/Mac)? If you can provide another screenshot of the half black door that would be great.

**Comment by marekjedrzejewski** [comment] 2014-03-08 12:18
![zrzut ekranu z 2014-03-08 13 13 39](https://f.cloud.github.com/assets/6793160/2365305/3e4a0fc6-a6bb-11e3-86a4-943423cfc9fc.png)
Yeah, it's just the monitors turning off, but because of shading problem the floor around  is completely black like objects mentioned in #150 and it looks like if it had no texture.

**Comment by mariodonofrio** [comment] 2014-03-19 17:15
Should be resolved in the next build.

**Comment by davidw-valve** [comment] 2014-03-25 00:49
This should be fixed now.

**Closed as completed by davidw-valve** 2014-03-25 00:49 UTC
Labels: not linux specific, Reviewed
