### ISSUE TITLE
GLaDOS' Eye

### ISSUE THREAD

**Issue by WillMcDade** [ValveSoftware/portal2#133] opened 2014-03-02 13:25 UTC
At the part of Wheatly waking GLaDOS, GLaDOS' eye has not got the orange light like in Windows.

SPEC:
HP dx5150 MT
AMD Athlon 64 X2 2.0GHz
3GB RAM
80GB Western Digital Caviar, 250GB Western Digital Caviar, 250GB Seagate Momentus
MSi GeForce GT N210
Arch Linux KDE

I was recording at the time so I can cut a clip out and post it if you want.

**Comment by timjp87** [comment] 2014-03-02 13:26
Duplicate of #27

**Comment by WillMcDade** [comment] 2014-03-02 13:27
Sorry about that @blackout24. Hadn't scrolled through. :)

**Closed as completed** 2014-03-04 19:42 UTC
Labels: duplicate
