### ISSUE TITLE
Spinning mouse in intro 

### ISSUE THREAD

**Issue by brealorg** [ValveSoftware/portal2#100] opened 2014-02-28 13:19 UTC
I tested the first level and the mouse kept returning to the roof and spinning round and round and round.

Tried to record a demo file, not sure if it's working or not. https://drive.google.com/file/d/0B8pYA1GggIAhSDgtY29LYWFBdzA/edit?usp=sharing

**Comment by timjp87** [comment] 2014-02-28 13:25
Duplicate of #16

**Comment by Tele42** [comment] 2014-02-28 21:12
I disagree, does not match the issue described in #16. This resembles https://github.com/ValveSoftware/halflife/issues/642.

**Comment by davidw-valve** [comment] 2014-03-05 01:00
Does this reproduce consistently on your machine?

**Comment by davidw-valve** [comment] 2014-03-06 00:16
I believe this should be fixed with updates since the report. It is hard to tell though since I couldn't reproduce this exactly.

I am closing the bug. Please re-open it if you can still repro it.

**Closed as completed by davidw-valve** 2014-03-06 00:16 UTC
Labels: Reviewed

**Comment by Tele42** [comment] 2014-03-06 00:51
@davidw-valve just a friendly reminder that users can not reopen issue reports by themselves which have been closed by a dev or moderator
