### ISSUE TITLE
Merasmus! Give me back my eye!

### ISSUE THREAD

**Issue by TapGhoul** [ValveSoftware/portal2#117] opened 2014-03-01 08:49 UTC
During sp_a1_wakeup, when GlaDOS is talking to you, her eye flickers in and out. It comes on for a second or so, and then disappears for another 3 or so, and it repeats, with the times being random (they on time being shorter though).

![2014-03-01_00017](https://f.cloud.github.com/assets/3120639/2301012/1b41d65a-a11e-11e3-8237-b3e2a6bf9888.jpg)

When you get closer, the eye comes back on, but is dim, and appears to just be a glowing sphere hovering.

![2014-03-01_00020](https://f.cloud.github.com/assets/3120639/2301014/26bed46a-a11e-11e3-81dc-e2fc0a69d691.jpg)

The shadows are also just plain squares while GlaDOS is starting up, when she's moving her body from dead to alive. They sweep a large area. They stop being squares, and return to normal when she has powered up.

![2014-03-01_00008](https://f.cloud.github.com/assets/3120639/2301015/36f64098-a11e-11e3-8141-6f7ac4f4f2dd.jpg)

![2014-03-01_00012](https://f.cloud.github.com/assets/3120639/2301020/47bd119a-a11e-11e3-8326-d9f8f92c221b.jpg)

I am using Linux.

**Comment by timjp87** [comment] 2014-03-01 10:09
Duplicate of #27

**Closed as completed** 2014-03-02 07:06 UTC
