### ISSUE TITLE
Emancipation Grill player direction change

### ISSUE THREAD

**Issue by KuriKai** [ValveSoftware/portal2#37] opened 2014-02-26 08:46 UTC
When walking though an Emancipation Grill the player direction changes about 10% to the right of the direction the player was walking (using right mouse button as move forward)
http://steamcommunity.com/id/kurikai/screenshots#scrollTop=0 for example

**Comment by timjp87** [comment] 2014-02-26 09:07
Can't confirm this here. I aim for the elevator, let go of the mouse and walk forward. Nothing strange happens.

**Comment by KuriKai** [comment] 2014-02-26 09:43
video capture of the problem
http://youtu.be/K-RVcBc0NLc

**Comment by dscharrer** [comment] 2014-02-26 11:22
Looks like a duplicate of #16, or at least some comments there mention the same problem

**Comment by TheDude7053** [comment] 2014-02-26 22:22
I can confirm this, Using Mouse and Keyboard going through emancipation grill, player turns 180 degrees.

**Comment by Arbitrary007** [comment] 2014-03-03 05:27
This should now be fixed. I used to have the issue and no longer at resolutions that caused it.

Also, looks to be a duplicate of #16, which is closed.

**Comment by davidw-valve** [comment] 2014-03-05 23:51
duplicate and should be fixed, so closing this out.

**Closed as completed by davidw-valve** 2014-03-05 23:51 UTC
Labels: Reviewed
