### ISSUE TITLE
Physics Problems

### ISSUE THREAD

**Issue by EliteTK** [ValveSoftware/portal2#91] opened 2014-02-27 20:31 UTC
There were no technical problems experienced when playing the game in single player.
There were, however, a few other problems:
- ~~Tangled ropes on elevator out of old aperture labs. [Already Reported]~~
- Raw mouse input option in keyboard / mouse settings is labelled as: "Ignore Windows Mouse Speed", this is, however, clearly not Windows and should probably just be labelled "Raw Mouse Input" instead.
- ~~The portal presence indicator ring around the cross-hair for blue portal device stays filled with blue even if the portal no longer exists. [Possibly not a Bug]~~
- ~~As you probably already know, the non beta version of Portal 2 is marked as beta anyway leading to "Portal 2 (Beta) [beta]" when the beta is opted into.~~
- Rare physics glitches, mainly when moving things through portals. When things have to rub past the edges of the portal strange things happen. This includes objects rapidly lerping between the portals without going through the portals and objects freezing stuck to the portal boundaries and only movable again when moving the portal.

That is all.

Thank you, this is a very good job for a beta.

Sprunge of some of my technical details: http://sprunge.us/CEaB

**Comment by Tele42** [comment] 2014-02-27 22:50
Meta-issue reports are explicitly discouraged because they are difficult to track properly. Please report one issue per issue report. Raw input covered by #11. Last fired portal color is not a bug from my memory. The labeling in steam is intentional and will stay that way barring some profound regression, it should be read as the beta branch of the platform beta of Portal 2. That leaves rare physics glitches, which does not appear to have been reported before.

**Comment by EliteTK** [comment] 2014-02-27 23:07
The raw input works fine. The only problem is the naming of the option in the menu. We're not in windows any more so "Ignore Windows Mouse Speed" is not the right name for the option.

With regards to the physics, I now added more info.

**Comment by panzi** [comment] 2014-02-28 00:01
Here are screenshots of a cube stuck in a portal:
![Cube stuck](http://cloud-3.steampowered.com/ugc/792936371030534079/3067FA8A220225CB5EA15E60B7B26277EA6A8879/)
![Cube stuck](http://cloud-4.steampowered.com/ugc/792936371030516749/83B69BFA6F9095EAD7DDAD084350D9651C8590A8/)

I think I was going backwards through the portal. Moving the portal freed the cube, but I could not grab it when it was stuck.

This only happened once for me in a single player play through (ignoring all achievements, as I always do).

**Comment by PARTYMANX** [comment] 2014-02-28 01:19
That physics issue also happened to me at the same location (The wheatley chamber with the orange gel ramp and funnel).  Oddly, if you put a portal on the floor by the large pit, it's fine (and that fixed the wall portal for me too)

**Comment by EliteTK** [comment] 2014-02-28 15:51
Good point, same location here too, but I also noticed problems in general when moving cubes through portals.

**Comment by ItsMeOnly** [comment] 2014-03-02 20:06
The physics issue also makes the "shortcut" in 1971 Aperture Science (skipping potatos) insanely difficult to achieve, because the player gets stuck in a portal or looses momentum required to achieve the jump.

**Comment by davidw-valve** [comment] 2014-03-05 01:07
I believe the remaining bugs reported here have all been duplicated in individual bug reports, so closing this.

**Closed as completed by davidw-valve** 2014-03-05 01:07 UTC
Labels: duplicate, Reviewed
