### ISSUE TITLE
Crashes to Desktop on play, Window with Borders mode

### ISSUE THREAD

**Issue by RecceDG** [ValveSoftware/portal2#41] opened 2014-02-26 10:53 UTC
Set video to Window With Borders. Set resolution to 1440 x 880 (I Ithink) Play, Single Player, Chapter 1. Various load screens then crash to desktop.

Ubuntu 12.04 LTS. Latest Catalyst drivers. Radeon 7880.

**Comment by RecceDG** [comment] 2014-02-26 11:23
This turns out to be CTD in _all_ graphics modes. Load screens then CTD.

Where are the logs stored?

**Comment by dscharrer** [comment] 2014-02-26 11:29
Duplicate of #4

> Where are the logs stored?

Close Steam, then run `steam` from a terminal and start the game. Log output should appear in the terminal.

**Comment by RecceDG** [comment] 2014-02-26 11:54
Starting steam from console worked.

Trying "The Fall" played the animation of the fall fine, then segfaulted and dumped core after the opening sequence played.

**Comment by dscharrer** [comment] 2014-02-26 12:02
If this is just the same as #4 you should close this issue and add your information there.

**Comment by davidw-valve** [comment] 2014-03-05 01:33
Closing as duplicate of #4

**Closed as completed by davidw-valve** 2014-03-05 01:33 UTC
Labels: duplicate
