### ISSUE TITLE
Controller - can not navigate trough Community Single player chambers

### ISSUE THREAD

**Issue by roman-bronis** [ValveSoftware/portal2#178] opened 2014-03-26 07:57 UTC
Navigation with controller is not working in:
Menu -> Community test chambers -> Play Single Player Chambers -> Single player chambers
A, B and X, Y are working though.

**Comment by stevethepocket** [comment] 2014-03-27 19:08
Duplicate of #176.

**Closed as completed** 2014-03-27 19:41 UTC
Labels: duplicate, Reviewed
