### ISSUE TITLE
Can't change the screen resolution

### ISSUE THREAD

**Issue by gabboman** [ValveSoftware/portal2#52] opened 2014-02-26 13:14 UTC
I use an intel HD graphics with the lastest mesa driver, and arch linux.
I can't change the resolution, when I push the button the system ignores my order and it's still at native resolution (1366x766).

My gpu is not so much powerfull so I must play it at 800x600 to the game become playable. What could I do? thanks :+1:

**Comment by Tele42** [comment] 2014-02-26 15:35
Duplicate of #2.

**Comment by davidw-valve** [comment] 2014-02-26 23:41
Closing as duplicate.

**Closed as completed by davidw-valve** 2014-02-26 23:41 UTC
Labels: duplicate
