### ISSUE TITLE
Linux openSUSE 13.1 64 bit Portal 2 crashes when loading a level

### ISSUE THREAD

**Issue by Gps2010** [ValveSoftware/portal2#85] opened 2014-02-27 12:14 UTC
I can start portal 2, then I click start new game, but when there are about two more dots to lit up, portal seems to crash or get into a loop.
System info:
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3210 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    "openSUSE 13.1 (Bottle) (x86_64)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.10-7-desktop
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403901
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  ATI Technologies Inc. ATI Radeon HD 5700 Series 

```
Driver Version:  4.3.12618 Compatibility Profile Context 13.25.18
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x68be
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 17,05" x 10,67"  (20,08" diag)
                                        43,3cm x 27,1cm  (51,0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  3958 Mb

Miscellaneous:
    UI Language:  English
    LANG:  nl_NL.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  447088 Mb
    Largest Free Hard Disk Block:  323689 Mb

Installed software:

Recent Failure Reports:
    Fri Nov 22 02:06:34 2013 GMT: file ''/tmp/dumps/crash_20131122030626_15.dmp'', upload no: ''Failure when receiving data from the peer''
    Sun Nov 24 15:43:37 2013 GMT: file ''/tmp/dumps/assert_20131124164324_4.dmp'', upload yes: ''CrashID=bp-1f50168a-c492-492e-bc45-8267b2131124''
    Sun Nov 24 15:44:06 2013 GMT: file ''/tmp/dumps/crash_20131124164359_4.dmp'', upload yes: ''CrashID=bp-ed721c60-7897-4ed5-88ec-1f5eb2131124''
    Sun Nov 24 15:45:31 2013 GMT: file ''/tmp/dumps/assert_20131124164324_2.dmp'', upload no: ''Couldn't connect to server''
    Sun Nov 24 15:46:07 2013 GMT: file ''/tmp/dumps/assert_20131124164359_6.dmp'', upload no: ''Couldn't connect to server''
    Mon Nov 25 23:33:58 2013 GMT: file ''/tmp/dumps/assert_20131126003333_5.dmp'', upload yes: ''CrashID=bp-ff7d50db-3b4f-484f-8a47-4cb572131125''
    Tue Nov 26 15:25:11 2013 GMT: file ''/tmp/dumps/assert_20131126162455_5.dmp'', upload no: ''Failure when receiving data from the peer''
    Fri Nov 29 12:05:27 2013 GMT: file ''/tmp/dumps/assert_20131129130505_5.dmp'', upload yes: ''CrashID=bp-718f6ebb-041e-4e3b-8c13-412452131129''
    Sat Nov 30 01:29:52 2013 GMT: file ''/tmp/dumps/assert_20131130022939_5.dmp'', upload yes: ''CrashID=bp-977b6a50-0166-4f5d-96f7-0b6f62131129''
    Thu Dec  5 18:12:44 2013 GMT: file ''/tmp/dumps/crash_20131205183933_15.dmp'', upload no: ''Failure when receiving data from the peer''
    Thu Feb  6 19:52:26 2014 GMT: file ''/tmp/dumps/crash_20140206205019_15.dmp'', upload no: ''Couldn't connect to server''
    Fri Feb 21 22:27:02 2014 GMT: file ''/tmp/dumps/crash_20140221232551_15.dmp'', upload yes: ''CrashID=bp-c16781c7-aa80-488a-bffe-079792140221''

Output form commandnline:
guus@linux-wovc:~> steam
Running Steam on opensuse 13.1 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)

(steam:19262): Gtk-WARNING **: Kan themamodule niet vinden in modulepad: ‘oxygen-gtk’,

(steam:19262): Gtk-WARNING **: Kan themamodule niet vinden in modulepad: ‘oxygen-gtk’,
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
[0227/130408:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0227/130408:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)

*\* (steam:19262): WARNING **: Could not initialize NMClient /org/freedesktop/NetworkManager: The name org.freedesktop.NetworkManager was not provided by any .service files

*\* (steam:19262): WARNING **: _nm_remote_settings_ensure_inited: (NMRemoteSettings) error initializing: The name org.freedesktop.NetworkManager was not provided by any .service files

Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Adding licenses for the following package(s): 0, 1, 425, 482, 2481, 2621, 4073, 4687, 7877, 12361, 16388, 17347, 18660, 27644, 38900
roaming config store loaded successfully - 2422 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
ExecCommandLine: "/home/guus/.local/share/Steam/ubuntu12_32/steam"
System startup time: 16,29 seconds
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
Running Steam on opensuse 13.1 64-bit
STEAM_RUNTIME has been set by the user to: /home/guus/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 72: 128x256, total string texture memory is 442,37 KB
Generating new string page texture 73: 128x256, total string texture memory is 131,07 KB
Generating new string page texture 74: 64x256, total string texture memory is 507,90 KB
Generating new string page texture 75: 32x256, total string texture memory is 540,67 KB
ExecCommandLine: "/home/guus/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 80: 24x256, total string texture memory is 565,25 KB
Generating new string page texture 96: 256x256, total string texture memory is 393,22 KB
Generating new string page texture 97: 128x256, total string texture memory is 696,32 KB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Generating new string page texture 104: 128x256, total string texture memory is 827,39 KB
Generating new string page texture 105: 256x256, total string texture memory is 1,09 MB
Generating new string page texture 106: 384x256, total string texture memory is 1,48 MB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Generating new string page texture 127: 128x256, total string texture memory is 1,61 MB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Game update: AppID 620 "Portal 2 (Beta)", ProcID 19437, IP 0.0.0.0:0
CGameStreamThread: Added instance ID 19437 for appid 620
CGameStreamThread: Set render instance ID 19437 for appid 620
ERROR: ld.so: object '/home/guus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
ERROR: ld.so: object '/home/guus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
pid 19439 != 19438, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/guus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object '/home/guus/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
CGameStreamThread: Added instance ID 19438 for appid 620
CGameStreamThread: Added instance ID 19440 for appid 620
SDL video target is 'x11'

CGameStreamThread: Added instance ID 19441 for appid 620
CGameStreamThread: Set render instance ID 19441 for appid 620
Installing breakpad exception handler for appid(gameoverlayui)/version(20140225134510_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number

(gameoverlayui:19446): Gtk-WARNING **: Kan themamodule niet vinden in modulepad: ‘oxygen-gtk’,

(gameoverlayui:19446): Gtk-WARNING **: Kan themamodule niet vinden in modulepad: ‘oxygen-gtk’,
[0227/130434:ERROR:object_proxy.cc(239)] Failed to call method: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
[0227/130434:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Setting breakpad minidump AppID = 620
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198026498389 [API loaded no]
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0_client)
Did not detect any valid joysticks.

CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'

Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
Did not detect any valid joysticks.
CSoundEmitterSystemBase::BaseInit:  Manifest 'scripts/game_sounds_manifest.txt' with bogus file type 'new_sound_scripts_must_go_below_here', expecting 'declare_file' or 'precache_file'
Convar r_flashlightscissor has conflicting FCVAR_CHEAT flags (child: no FCVAR_CHEAT, parent: has FCVAR_CHEAT, parent wins)

 ##### swap interval = 1     swap limit = 1 #####
OnFocusWindowChanged to window type: k_EWindowTypeGame, 620
CClientSteamContext logged on = 1

Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)

Game.dll loaded for "Half-Life 2"

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(portal2_linux)/version(1.0_client)
CClientSteamContext logged on = 1
Convar building_cubemaps has conflicting FCVAR_CHEAT flags (child: has FCVAR_CHEAT, parent: no FCVAR_CHEAT, parent wins)
Game.dll loaded for "Half-Life 2"
/home/guus/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: regel 46: 19441 Afgebroken              ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 19441 
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:19262): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
Generating new string page texture 144: 8x256, total string texture memory is 1,62 MB
Steam: An X Error occurred
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  40 (X_TranslateCoords)
Resource id in failed request:  0x200052f
Serial number of failed request:  6057
xerror_handler: X failed, continuing
OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
Generating new string page texture 145: 256x256, total string texture memory is 1,88 MB
OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0

Other games like portal 1 and Half Life 2 work without issues.

**Comment by timjp87** [comment] 2014-02-27 12:16
Duplicate of #4

**Comment by Gps2010** [comment] 2014-02-27 12:43
Sigh, I had read the issues list but must have over looked this one. Me bad.
Besides him using arch it seems to be the same prob.
From earlier experience I noticed Arch and openSUSE seem to have the same issues. ( and solutions)

**Comment by istvan-v** [comment] 2014-02-27 17:25
It does not crash for me on openSUSE 13.1 (x86_64) with nVidia 331.20 drivers. The problem could be related to the AMD Catalyst drivers.

**Comment by timjp87** [comment] 2014-02-27 17:42
@istvan-v No check the first tracked issue #4 also some people with NVIDIA drivers get crashs but they are more rare.

**Comment by istvan-v** [comment] 2014-02-27 17:50
That could be a different issue, though; some people get similar crashes even on Windows. Also, at #4 it has been reported that switching to the open source Radeon drivers fixed the crash.

**Comment by davidw-valve** [comment] 2014-03-05 22:19
Closing as duplicate of #4

**Comment by Gps2010** [comment] 2014-03-07 01:40
Latest portal 2 update, seems to have fixed it. 

I was able to start a new game.
Looked at the painting and I ended up in the first test chamber.
Thank you guys.

**Closed as completed** 2014-03-10 17:03 UTC
Labels: duplicate, Reviewed, GPU: ATI
