### ISSUE TITLE
homepage UI show nothing

### ISSUE THREAD

**Issue by a7083399** [ValveSoftware/portal2#368] opened 2022-01-07 12:24 UTC
System:   Debian / 64-bit,    GNOME 41.2 ,   X11
CPU:  Intel i5-7400  *4 
GPU:  Nvidia GTX 1050ti,  nvidia-driver  version is  470.86

I start the game  sucessfully  but  homepage  all selections  are blank, it show no one word

**Comment by a7083399** [comment] 2022-01-07 12:25
![Screenshot from 2022-01-07 19-56-45](https://user-images.githubusercontent.com/11836822/148543920-f5074bb9-885e-4309-9f2f-3f29841e0b58.png)
![Screenshot from 2022-01-07 19-56-48](https://user-images.githubusercontent.com/11836822/148543937-f29b93f0-b9b1-4759-983b-3135f2df077d.png)

**Comment by kisak-valve** [comment] 2022-01-07 13:50
Hello @a7083399, this looks like #200 / #134. Can you give them a read and see if you're seeing the same issue discussed there? What language do you have the game configured to run with?

**Comment by a7083399** [comment] 2022-01-07 15:34
> Hello @a7083399, this looks like #200 / #134. Can you give them a read and see if you're seeing the same issue discussed there? What language do you have the game configured to run with?

Thanks  @kisak-valve 
My system-LANG is  en_US, the steam language is English , and  this is my first time to play  portal2,  I dont know which fonts and language  is the default in game.  

But anyway, I found the solution in #346   by  creating  the font.conf  and  launch  with command.  It  displays Simple-Chinese and works fine.

Thanks again :)

**Comment by kisak-valve** [comment] 2022-01-07 15:46
Glad to hear the workaround had an effect, that makes your issue a duplicate of #200. Closing.

**Closed as completed by kisak-valve** 2022-01-07 15:46 UTC
